README.md, src/spacectl/command/api_resource.py, src/spacectl/command/config.py, src/spacectl/command/endpoint.py, src/spacectl/command/execute.py, src/spacectl/command/template.py, src/spacectl/command/version.py, src/spacectl/conf/my_conf.py, src/spacectl/lib/parser/default.py, src/spacectl/main.py
=> Change import path

src/setup.py, src/spacectl/conf/global_conf.py
=> Bug Fix: template.yml import issue

src/spacectl/command/api_resource.py, src/spacectl/command/config.py, src/spacectl/command/execute.py, src/spacectl/conf/global_conf.py, src/spacectl/conf/my_conf.py, src/spacectl/main.py
=> add namespace feature

README.md
documenting basic usage of spacectl
=> Updated README.md to documenting basic usage of spacectl

src/spacectl/main.py
=> If not installed as package, set source root to python environment

src/spacectl/command/version.py
Remove unnecessary print comment
=> Remove unnecessary print comment

src/spacectl/command/config.py, src/spacectl/command/execute.py
=> Change domain_id and api_key to optional settings

README.md, src/spacectl/command/config.py, src/spacectl/main.py
=> Change document

src/spacectl/command/api_resource.py, src/spacectl/command/execute.py
=> Change error message when api error

src/spacectl/command/execute.py, src/spacectl/lib/output.py
=> Add a csv option for output

src/spacectl/lib/output.py
=> Bug fix: quiet output mode

src/spacectl/command/execute.py
=> Remove sort option from stat command

src/spacectl/lib/parser/default.py
=> Remove debug code

src/spacectl/lib/parser/default.py
=> Change parser utils

src/spacectl/lib/parser/default.py
=> Fix a tags column bug

src/spacectl/lib/parser/default.py
=> Fix a tags field bug

src/spacectl/template/inventory.Server.yml
=> fix: fix server template

.github/PULL_REQUEST_TEMPLATE.md, docs/apply.md, src/setup.py, src/spacectl/command/execute.py, src/spacectl/lib/apply/task_manager.py, src/spacectl/lib/template.py, src/spacectl/modules/__init__.py, src/spacectl/modules/export_google_sheets/export_google_sheets_task.py, src/spacectl/modules/resource/resource_task.py
feat: add output feature in resource task (#54 )
feat: add export google sheets task (#53 )
etc: add PULL_REQUEST_TEMPLATE.md
Refer the README document Please. (https://github.com/spaceone-dev/spacectl/blob/master/docs/apply.md)
=> feat: add export google sheets modules

src/spacectl/command/execute.py
Add method options to list and stat commands for changing API methods
=> feat: add method option to list and stat commands

src/spacectl/command/execute.py
=> fix: fix parser bug

src/spacectl/command/execute.py
Fix an argument bug in get command
=> fix: fix argument bug

src/spacectl/command/execute.py, src/spacectl/modules/resource/resource_task.py
=> feat: support grpc stream response

docs/apply.md
docs: update README.md for apply command.
Add template feature in apply (https://github.com/spaceone-dev/spacectl/issues/54)
Add output module : export google sheets (https://github.com/spaceone-dev/spacectl/issues/53)
=> docs: update README.md for apply

src/spacectl/modules/resource/resource_task.py
fix: show optional column when metadata is from config server
Add template feature in apply: #54
=> fix: show optional column when metadata is from config server

src/spacectl/command/execute.py
fix error when responding to grpc stream
=> fix: fix error when responding to grpc stream

src/spacectl/command/execute.py
=> fix: fix typo

src/spacectl/lib/apply/task_manager.py, src/spacectl/modules/export_google_sheets/__init__.py, src/spacectl/modules/resource/__init__.py
=> refactor: reactor apply command

src/spacectl/lib/apply/task_manager.py, src/spacectl/modules/export_google_sheets/__init__.py
=> refactor apply commands

src/setup.py
=> build: add require package (google-api-core)

src/spacectl/modules/resource/__init__.py
=> refactor: change the syntax for python version compatibility

src/setup.py, src/spacectl/command/execute.py, src/spacectl/lib/apply/task_manager.py, src/spacectl/lib/output.py, src/spacectl/lib/parser/__init__.py, src/spacectl/lib/parser/default.py, src/spacectl/lib/template.py, src/spacectl/modules/__init__.py, src/spacectl/modules/export_mysql.py, src/spacectl/modules/export_s3.py, src/spacectl/modules/join.py, src/spacectl/modules/resource/__init__.py
- add export-s3 module
- add export-mysql module
- refactor template engine
=> Improve "apply" command
